apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-deployment
  labels:
    app: metadata-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-pod
  template:
    metadata:
      labels:
        app: metadata-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  labels:
    app: metadata-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: metadata-pod
